
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{settingsTemplate}

\DeclareOption*{\PassOptionsToClass{\CurrentOption}{report}}
\ProcessOptions\relax
\LoadClass[a4paper]{report}

\RequirePackage{graphicx}
\RequirePackage{ifthen}

\RequirePackage[a4paper]{geometry}

\raggedbottom

%define the default submitted text
\newcommand{\submittedtext}{{A thesis submitted for the degree of}}
\newcommand{\course}{{COURSE NAME}}

\def\degreedate#1{\gdef\@degreedate{#1}}
\def\degree#1{\gdef\@degree{#1}}
\def\department#1{\gdef\@department{#1}}
\def\university#1{\gdef\@university{#1}}

% you need an unilogo.eps or unilogo.pdf file as appropriate
\def\logo{{\includegraphics[width=35mm]{unilogo}}}


% This macro define an environment for front matter that is always 
% single column even in a double-column document.

\newenvironment{alwayssingle}{%
       \@restonecolfalse
       \if@twocolumn\@restonecoltrue\onecolumn
       \else\if@openright\cleardoublepage\else\clearpage\fi
       \fi}%
       {\if@restonecol\twocolumn
       \else\newpage\thispagestyle{empty}\fi}

%define title page layout
\renewcommand{\maketitle}{%
\newgeometry{left=25mm,right=25mm,top=15mm,bottom=15mm}
\begin{alwayssingle}
    \renewcommand{\footnotesize}{\small}
    \renewcommand{\footnoterule}{\relax}
    \thispagestyle{empty}
    \null\vfill
    \begin{center}
        \begin{center}\logo\end{center}
        \vspace{4mm}
        
        {\scshape\LARGE {\textbf{\@university}} \par}
        \vspace{4mm}
        
        {\scshape \large {\textbf{\@department}} \par}
        \vspace{4mm}
        
        {\scshape \large {\textbf{Corso di Laurea \@degree}} \par}
        \vspace{8mm}
        
        {\noindent\rule{160mm}{0.8pt} \par}
        \vspace{8mm}
        
        {\bfseries \scshape \large \submittedtext \par}
        {\bfseries \scshape \large \course \par}
        \vspace{10mm}
        
        {\scshape \Large \bfseries \@title \par}
        \vspace{30mm}
    \end{center}
    
    {\scshape \noindent \bfseries Relatore: \par}
    {\scshape \noindent\bfseries Chiar.mo Prof./Dott. Nome Cognome \par}
    \vspace{8mm}
    
    {\scshape \noindent \bfseries Correlatori: \par}
    {\scshape \noindent \bfseries Prof./Dott. Nome Cognome \par}
    {\scshape \noindent \bfseries Prof./Dott. Nome Cognome \par}
    \vspace{10mm}
    
    \begin{flushright}
    {\scshape \bfseries Laureando: \par}
    {\scshape \bfseries \@author \par}
    \end{flushright}
    
    \begin{center} 
        {\noindent\rule{160mm}{0.8pt} \par} 
        {\bfseries ANNO ACCADEMICO 0000-0000 \par}
    \end{center}
    \null\vfill
\end{alwayssingle}
% Define text area of page and margin offsets for the rest of the document
%
\restoregeometry
\setlength{\topmargin}{0.0in}
\setlength{\oddsidemargin}{1.46cm}
\setlength{\evensidemargin}{-0.54cm}
\setlength{\marginparwidth}{0pt}
\setlength{\marginparsep}{2cm}
\setlength{\textheight}{9.0in}
\setlength{\textwidth}{15cm}}

% DEDICATION
%
% The dedication environment makes sure the dedication gets its
% own page and is set out in verse format.

\newenvironment{dedication}
{\begin{alwayssingle}
  \thispagestyle{empty}
  \begin{center}
  \vspace*{1.5cm}
  {\LARGE }
  \end{center}
  \vspace{0.5cm}
  \begin{verse}\begin{center}}
{\end{center}\end{verse}\end{alwayssingle}}


% ACKNOWLEDGEMENTS
%
% The acknowledgements environment puts a large, bold, centered 
% "Acknowledgements" label at the top of the page. The acknowledgements
% themselves appear in a quote environment, i.e. tabbed in at both sides, and
% on its own page.

\newenvironment{acknowledgements}
{\begin{alwayssingle} \thispagestyle{empty}
\begin{center}
\vspace*{1.5cm}
{\Large \bfseries Acknowledgements}
\end{center}
\vspace{0.5cm}
\begin{quote}}
{\end{quote}\end{alwayssingle}}

% The acknowledgementslong environment puts a large, bold, centered 
% "Acknowledgements" label at the top of the page. The acknowledgement itself 
% does not appears in a quote environment so you can get more in.

\newenvironment{acknowledgementslong}
{\begin{alwayssingle} \thispagestyle{empty}
\begin{center}
\vspace*{1.5cm}
{\Large \bfseries Acknowledgements}
\end{center}
\vspace{0.5cm}}
{\end{alwayssingle}}

% STATEMENT OF ORIGINALITY (AS SUGGESTED BY GSW)
%
% The originality environment puts a large, bold, centered 
% "Statement of originality" label at the top of the page. The statement 
% of originality itself appears in a quote environment, i.e. tabbed in at 
% both sides, and on its own page.

\newenvironment{originality}
{\begin{alwayssingle} \thispagestyle{empty}
\begin{center}
\vspace*{1.5cm}
{\Large \bfseries Statement of Originality}
\end{center}
\vspace{0.5cm}
\begin{quote}}
{\end{quote}\end{alwayssingle}}

% The originalitylong environment puts a large, bold, centered 
% "Statement of originality" label at the top of the page. The statement 
% of originality itself does not appears in a quote environment so you can 
% get more in.

\newenvironment{originalitylong}
{\begin{alwayssingle} \thispagestyle{empty}
\begin{center}
\vspace*{1.5cm}
{\Large \bfseries Statement of Originality}
\end{center}
\vspace{0.5cm}}
{\end{alwayssingle}}


%ABSTRACT
%
%The abstract environment puts a large, bold, centered "Abstract" label at
%the top of the page. The abstract itself appears in a quote environment,
%i.e. tabbed in at both sides, and on its own page.

\renewenvironment{abstract} {\begin{alwayssingle} \thispagestyle{empty}
  \begin{center}
  \vspace*{1.5cm}
  {\Large \bfseries  Abstract}
  \end{center}
  \vspace{0.5cm}
   \begin{quote}}
{\end{quote}\end{alwayssingle}}

%The abstractlong environment puts a large, bold, centered "Abstract" label at
%the top of the page. The abstract itself does not appears in a quote
%environment so you can get more in.

\newenvironment{abstractlong} {\begin{alwayssingle} \thispagestyle{empty}
  \begin{center}
  \vspace*{1.5cm}
  {\Large \bfseries  Abstract}
  \end{center}
  \vspace{0.5cm}}
{\end{alwayssingle}}

%The abstractseparate environment is for running of a page with the abstract
%on including title and author etc as required to be handed in separately

\newenvironment{abstractseparate} {\begin{alwayssingle} \thispagestyle{empty}
  \vspace*{-1in}
 \begin{center}
    { \Large {\bfseries {\@title}} \par}
    {{\large \vspace*{1ex} \@author} \par}
{\large \vspace*{1ex}
    {{\@department} \par}
    {{\@university} \par}
\vspace*{1ex}
    {{\it \submittedtext} \par}
    {\it {\@degree} \par}
\vspace*{2ex}
    {\@degreedate}}
  \end{center}}
{\end{alwayssingle}}

%ROMANPAGES
%
% The romanpages environment set the page numbering to lowercase roman one
% for the contents and figures lists. It also resets
% page-numbering for the remainder of the dissertation (arabic, starting at 1).

\newenvironment{romanpages}
{\cleardoublepage\setcounter{page}{1}\renewcommand{\thepage}{\roman{page}}}
{\cleardoublepage\renewcommand{\thepage}{\arabic{page}}\setcounter{page}{1}}






